# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  smallbank-tp-go:
    build:
      context: .
      dockerfile: examples/smallbank/smallbank_go/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-smallbank-tp-go:${ISOLATION_ID}
    container_name: sawtooth-smallbank-tp-go-default

  sawtooth-intkey-tp-go:
    build:
      context: .
      dockerfile: examples/intkey_go/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-intkey-tp-go:${ISOLATION_ID}
    container_name: sawtooth-intkey-tp-go-default

  sawtooth-noop-tp-go:
    build:
      context: .
      dockerfile: examples/noop_go/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-noop-tp-go:${ISOLATION_ID}
    container_name: sawtooth-noop-tp-go-default

  sawtooth-xo-tp-go:
    build:
      context: .
      dockerfile: examples/xo_go/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-xo-tp-go:${ISOLATION_ID}
    container_name: sawtooth-xo-tp-go-default
